/**
 * Sidebar configuration for layline.io documentation.
 * Explicitly defines the two new asset categories:
 *   - Workflow Assets (everything under 03-assets except deployment)
 *   - Deployment Assets (the new deployment/ subdirectory)
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  mainSidebar: [
    {
      type: 'link',
      label: 'Landing page',
      href: '/',
    },
    {
      type: 'autogenerated',
      dirName: '01-quickstart',
    },
    {
      type: 'autogenerated',
      dirName: '02-concept',
    },
    {
      type: 'category',
      label: 'Workflow Assets',
      link: {
        type: 'doc',
        id: 'assets/index',
      },
      items: [

        { type: 'autogenerated', dirName: 'assets/connections' },
        { type: 'autogenerated', dirName: 'assets/extensions' },
        { type: 'autogenerated', dirName: 'assets/formats' },
        { type: 'autogenerated', dirName: 'assets/processors-flow' },
        { type: 'autogenerated', dirName: 'assets/processors-input' },
        { type: 'autogenerated', dirName: 'assets/processors-output' },
        { type: 'autogenerated', dirName: 'assets/resources' },
        { type: 'autogenerated', dirName: 'assets/services' },
        { type: 'autogenerated', dirName: 'assets/sinks' },
        { type: 'autogenerated', dirName: 'assets/sources' },
        { type: 'autogenerated', dirName: 'assets/workflows' },
      ],
    },
    {
      type: 'category',
      label: 'Deployment Assets',
      link: {
        type: 'doc',
        id: 'assets/deployment/index',
      },
      items: [
        { type: 'autogenerated', dirName: 'assets/deployment' },
      ],
    },
    {
      type: 'autogenerated',
      dirName: '04-language-reference',
    },
    {
      type: 'autogenerated',
      dirName: '07-operations',
    },
    {
      type: 'autogenerated',
      dirName: '08-release-notes',
    },
    {
      type: 'link',
      label: 'Corporate website',
      href: 'https://layline.io',
    },
  ],
};

module.exports = sidebars;
