/**
 * Creating a sidebar enables you to:
 * - create an ordered group of docs
 * - render a sidebar for each doc of that group
 * - provide next/previous navigation
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
    mainSidebar: [
        {
            type: 'link',
            label: 'Landing page',
            href: '/'
        },
        {
            type: 'autogenerated',
            dirName: '01-quickstart'
        },
        {
            type: 'autogenerated',
            dirName: '02-concept'
        },
        {
            type: 'category',
            label: 'Assets',
            collapsed: false,
            link: {
                type: 'doc',
                id: 'assets/index'
            },
            items: [
                {
                    type: 'category',
                    label: 'Workflow Assets',
                    collapsed: false,
                    items: [
                        {
                            type: 'doc',
                            id: 'assets/connections/index',
                            label: 'Connections',
                        },
                        {
                            type: 'doc',
                            id: 'assets/extensions/index',
                            label: 'Extensions',
                        },
                        {
                            type: 'doc',
                            id: 'assets/formats/index',
                            label: 'Formats',
                        },
                        {
                            type: 'doc',
                            id: 'assets/processors-flow/index',
                            label: 'Processors (Flow)',
                        },
                        {
                            type: 'doc',
                            id: 'assets/processors-input/index',
                            label: 'Processors (Input)',
                        },
                        {
                            type: 'doc',
                            id: 'assets/processors-output/index',
                            label: 'Processors (Output)',
                        },
                        {
                            type: 'doc',
                            id: 'assets/resources/index',
                            label: 'Resources',
                        },
                        {
                            type: 'doc',
                            id: 'assets/services/index',
                            label: 'Services',
                        },
                        {
                            type: 'doc',
                            id: 'assets/sinks/index',
                            label: 'Sinks',
                        },
                        {
                            type: 'doc',
                            id: 'assets/sources/index',
                            label: 'Sources',
                        },
                        {
                            type: 'doc',
                            id: 'assets/workflows/index',
                            label: 'Workflows',
                        },
                    ]
                },
                {
                    type: 'category',
                    label: 'Deployment Assets',
                    collapsed: false,
                    link: {
                        type: 'doc',
                        id: 'assets/deployment/index'
                    },
                    items: [
                        { type: 'autogenerated', dirName: '03-assets/deployment' },
                    ]
                },
            ]
        },
        {
            type: 'autogenerated',
            dirName: '04-language-reference'
        },
        {
            type: 'autogenerated',
            dirName: '07-operations'
        },
        {
            type: 'autogenerated',
            dirName: '08-release-notes'
        },
        {
            type: 'link',
            label: 'Corporate website',
            href: 'https://layline.io'
        }
    ],
};

module.exports = sidebars;
