/**
 * Creating a sidebar enables you to:
 * - create an ordered group of docs
 * - render a sidebar for each doc of that group
 * - provide next/previous navigation
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
    mainSidebar: [
        {
            type: 'link',
            label: 'Landing page',
            href: '/'
        },
        {
            type: 'autogenerated',
            dirName: '01-quickstart'
        },
        {
            type: 'autogenerated',
            dirName: '02-concept'
        },
        {
            type: 'category',
            label: 'Assets',
            collapsed: false,
            link: {
                type: 'doc',
                id: 'assets/index'
            },
            items: [
                {
                    type: 'category',
                    label: 'Workflow Assets',
                    link: {
                        type: 'doc',
                        id: 'assets/index'
                    },
                    items: [
                        { type: 'autogenerated', dirName: '03-assets/connections' },
                        { type: 'autogenerated', dirName: '03-assets/extensions' },
                        { type: 'autogenerated', dirName: '03-assets/formats' },
                        { type: 'autogenerated', dirName: '03-assets/processors-flow' },
                        { type: 'autogenerated', dirName: '03-assets/processors-input' },
                        { type: 'autogenerated', dirName: '03-assets/processors-output' },
                        { type: 'autogenerated', dirName: '03-assets/resources' },
                        { type: 'autogenerated', dirName: '03-assets/services' },
                        { type: 'autogenerated', dirName: '03-assets/sinks' },
                        { type: 'autogenerated', dirName: '03-assets/sources' },
                        { type: 'autogenerated', dirName: '03-assets/workflows' },
                    ]
                },
                {
                    type: 'category',
                    label: 'Deployment Assets',
                    link: {
                        type: 'doc',
                        id: 'assets/deployment/index'
                    },
                    items: [
                        { type: 'autogenerated', dirName: '03-assets/deployment' },
                    ]
                },
            ]
        },
        {
            type: 'autogenerated',
            dirName: '04-language-reference'
        },
        {
            type: 'autogenerated',
            dirName: '07-operations'
        },
        {
            type: 'autogenerated',
            dirName: '08-release-notes'
        },
        {
            type: 'link',
            label: 'Corporate website',
            href: 'https://layline.io'
        }
    ],
};

module.exports = sidebars;
